"""add description and image_public_id

Revision ID: 02a6b72bee7a
Revises: aa4695694d3a
Create Date: 2026-02-22 22:06:07.320689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02a6b72bee7a'
down_revision: Union[str, Sequence[str], None] = 'aa4695694d3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('image_public_id', sa.String(), nullable=True))
    op.add_column('tests', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tests', 'description')
    op.drop_column('questions', 'image_public_id')
    # ### end Alembic commands ###
