"""add is_active to tests

Revision ID: fbd326e0bd12
Revises: 02a6b72bee7a
Create Date: 2026-02-23 22:00:42.778851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbd326e0bd12'
down_revision: Union[str, Sequence[str], None] = '02a6b72bee7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tests', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tests', 'is_active')
    # ### end Alembic commands ###
